language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-android-28
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'Build-tools'
    - '28.0.2 Android SDK Build-Tools 28.0.2'
before_install:
    - yes | sdkmanager "platforms;android-27"
script:
    - ./gradlew test
